### PR TITLE
Libadwaita tests

### PR DESCRIPTION
**Pull request by vchernin**
Note this isn't yet the latest libadwaita build (you can get that+gtk 4.5 easily with master runtime though).

Also the autostart won't work. The patch needs reworking since https://github.com/wwmm/easyeffects/commit/e55c7f5e3bd2c5c475e5519a799b976c6814a988, but since it needs to be redone anyway I'll just leave it commented out. 

Kindly ignore my messy git history, this is just for testing anyhow

### CODE REVIEW

**Comment by bhack** [comment]
Do you think that we could push this in the beta chanell?

**Comment by vchernin** [comment]
Yeah I'd like a beta or nightly branch here at some point (as mentioned in another issue). But I'd need to figure out how to easily auto update it with x-checker-data first without taking too much of Flathub builder's time.

Also I'd like to take a look at the autostart patch and see if I can throw something together.

**Comment by vchernin** [comment]
Pending some more testing, this latest commit should be suitable to put in flathub-beta, thanks to this fun little action https://github.com/vchernin/nightly-easyeffects-checker/blob/main/.github/workflows/nightly-checker.yml

**Comment by vchernin** [comment]
superseeded by #40

**Pull request closed without merging**
