### PR TITLE
41 runtime

### PR DESCRIPTION
**Pull request by vchernin**

### CODE REVIEW

**Comment by Eonfge** [comment]
Hey, normally I wouldn't directly interfere with other packages, but are you sure that Zenity is removed? It is a part of the FreeDesktop runtime.

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1268

**Comment by vchernin** [comment]
@Eonfge [The GNOME runtime specifically removed it](https://gitlab.gnome.org/GNOME/gnome-build-meta/-/merge_requests/1194).

**Comment by vchernin** [comment]
@wwmm the Flatpak is now using the gnome 41 runtime, which includes gtk 4.4 as well as newer GCC and meson.

**Comment by wwmm** [comment]
Ok

**Pull request merged**
