### PR TITLE
Popover auto hide fix test

### PR DESCRIPTION
**Pull request by vchernin**

### CODE REVIEW

**Comment by wwmm** [comment]
The `tbb` library is a new dependency. Let me know if it will be too hard to add it. On Arch Linux they are using tbb `2020.3` instead of the latest release. I do not know if there is a reason for that.

**Comment by vchernin** [comment]
I've tried the latest one, some seem to have trouble with newer builds: https://github.com/flathub/org.cloudcompare.CloudCompare/blob/d2ac52a71eb0a6774267c9a5bafb9d1b2c1d21b3/org.cloudcompare.CloudCompare.yaml#L133

It's a bit concerning Arch is so far behind. Potentially some packages have incompatibilities with newer tbb so they left it on the older one.

If distros and Flathub use different tbb versions that sounds like potential for problems. But tbb is useful looking library so I don't think it should be dropped because of this.

**Comment by wwmm** [comment]
For some reason tbb is required to use the parallel version of functions from c++ standard library. As the new convolver feature that allows impulse responses to be combined is being implemented with direct convolution I had to use the parallel version of the for loop to accelerated things a little bit.

**Comment by vchernin** [comment]
Hm, even on Wayland I find the experience with autohide disabled to be not good. I was just trying to check settings and it was very strange not being able to click outside the popover to close settings. This seems like a tricky issue.

Maybe this new impulse menu is the only place autohide should be disabled?

Also with impulse responses, I found a UX quirk. If you try to combine 2 files but not give a name, it doesn't highlight the fact you missed a name. Admittedly it would be strange to not give it a name, but it's confusing if you forget and just try to combine impulses quickly.

**Comment by vchernin** [comment]
From reading bug reports this VFX issue seems to be blocking tbb 2021 from Arch: https://bugs.archlinux.org/task/46160#comment202742

**Comment by wwmm** [comment]
>I was just trying to check settings and it was very strange not being able to click outside the popover to close settings.

I agree. It is annoying. In gtk3 the behavior was better. The popover was closed when clicking somewhere on the application window. Now when autohide is disabled only clicking on the menu button closes it.

>Maybe this new impulse menu is the only place autohide should be disabled?

It is something to consider as it is not clear when the gtk4 bug I reported will be fixed.

>If you try to combine 2 files but not give a name, it doesn't highlight the fact you missed a name.

Yes. I have to think about a way to notify the user about this.

> is it known that you can open both the Impulses and Combine menu at once? Is that intended or another bug?

It is a side effects of disabling the autohide.

**Comment by vchernin** [comment]
> Yes. I have to think about a way to notify the user about this.

A simple way could be to give the name box a red outline instead of blue when the user tries that.

**Comment by wwmm** [comment]
>A simple way could be to give the name box a red outline instead of blue when the user tries that, not sure how easy that is in GTK.

It would be nice. But I have the feeling it may not be an easy thing to do...

**Comment by wwmm** [comment]
In the end it was easy
Screenshot from 2021-10-30 17-30-28

**Pull request closed without merging**
