### PR TITLE
v7.1.9

### PR DESCRIPTION
**Pull request by vchernin**

### CODE REVIEW

**Comment by violetmage** [comment]
Is there a way to restart the test build? The bot doesn't seem to have received the request.

**Comment by vchernin** [comment]
> Is there a way to restart the test build? The bot doesn't seem to have received the request.

I think the issue is there are simply too many builds ongoing currently https://buildbot.flathub.org/#/. But if after a few hours it still does not show up, one can comment https://docs.flathub.org/docs/for-app-authors/maintenance#test-builds-and-pull-requests.

**Comment by violetmage** [comment]
I found the queue, it is indeed very busy today: [https://buildbot.flathub.org/#/pendingbuildrequests](https://buildbot.flathub.org/#/pendingbuildrequests)

**Comment by violetmage** [comment]
A quick, cursory test of this build seems all good for me so far.

**Pull request merged**
